import React, { useState } from 'react';
import { StyleSheet, Text, View, Button, ActivityIndicator } from 'react-native';
import { supabase } from '../lib/supabase';

export default function DevHarnessScreen() {
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const runHealthcheck = async () => {
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      // Query a small healthcheck table to validate connectivity and RLS.
      const { data, error: queryError } = await supabase
        .from('healthcheck')
        .select('id')
        .limit(1);

      if (queryError) {
        // If table doesn't exist, show helpful message
        if (queryError.message.includes('does not exist') || queryError.code === '42P01') {
          setError(
            'The "healthcheck" table is not defined in your Supabase project.\n\n' +
            'To create it, run this SQL in your Supabase SQL Editor:\n\n' +
            'CREATE TABLE public.healthcheck (\n' +
            '  id bigint generated by default as identity primary key\n' +
            ');\n' +
            'ALTER TABLE public.healthcheck ENABLE ROW LEVEL SECURITY;\n' +
            'CREATE POLICY "Allow anon read" ON public.healthcheck\n' +
            '  FOR SELECT TO anon USING (true);'
          );
        } else {
          setError(queryError.message);
        }
        return;
      }

      setResult(JSON.stringify(data, null, 2));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Dev Harness</Text>
      <Text style={styles.description}>
        Test Supabase connectivity by reading the healthcheck table
      </Text>

      <View style={styles.buttonContainer}>
        <Button
          title="Run healthcheck"
          onPress={runHealthcheck}
          disabled={loading}
        />
      </View>

      {loading && (
        <View style={styles.resultContainer}>
          <ActivityIndicator size="large" color="#0000ff" />
          <Text style={styles.loadingText}>Executing query...</Text>
        </View>
      )}

      {error && (
        <View style={styles.resultContainer}>
          <Text style={styles.errorLabel}>Error:</Text>
          <Text style={styles.errorText}>{error}</Text>
        </View>
      )}

      {result && (
        <View style={styles.resultContainer}>
          <Text style={styles.resultLabel}>Result:</Text>
          <Text style={styles.resultText}>{result}</Text>
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  description: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 24,
  },
  buttonContainer: {
    marginVertical: 16,
  },
  resultContainer: {
    marginTop: 24,
    padding: 16,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 8,
    color: '#666',
  },
  resultLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  resultText: {
    fontSize: 14,
    color: '#007AFF',
    fontFamily: 'monospace',
  },
  errorLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FF3B30',
    marginBottom: 8,
  },
  errorText: {
    fontSize: 14,
    color: '#FF3B30',
  },
});
